use master
go
create database SORIA_DB
go
USE SORIA_DB
go

/****** Object:  Table [dbo].[USUARIO]    Script Date: 01/05/2019 11:00:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSONAS](
	[ID]		  [INT] NOT NULL IDENTITY(1,1),
	[NOMBRE]	  [VARCHAR](50)NOT NULL,
	[APELLIDO]	  [VARCHAR](50)NOT NULL,
	[DNI]		  [VARCHAR](10)NOT NULL,
	[NACIMIENTO]  [DATE]NOT NULL CHECK(DATEDIFF(DAY,NACIMIENTO,GETDATE())>0),
	[EMAIL]		  [VARCHAR](60)NOT NULL,
	[Contraseña]  [VARCHAR](30)NOT NULL,
	[Perfil] [VARCHAR](13)NOT NULL check(Perfil = 'Administrador' or Perfil = 'Usuario' 
											or Perfil = 'Cliente' or Perfil = 'Proveedor'),

 CONSTRAINT [PK_PERSONAS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PRODUCTOS](
	[ID]			[BIGINT] NOT NULL IDENTITY(1,1),
	[NOMBRE]		[VARCHAR](50)NOT NULL,
	[PRECIOVENTA]	[DECIMAL](8,2)NOT NULL CHECK(PRECIOVENTA >=0),
	[PRECIOCOMPRA]	[DECIMAL](8,2)NOT NULL CHECK(PRECIOVENTA >=0),
	[STOCK]			[INT]NOT NULL CHECK(STOCK >=0),
	[STOCKMIN]		[INT]NOT NULL CHECK(STOCKMIN >=0),
	[STOCKMAX]		[INT]NOT NULL CHECK(STOCKMAX >=0),
	[VENCIMIENTO]	[DATE]NOT NULL CHECK(DATEDIFF(DAY,VENCIMIENTO,GETDATE())<0),

 CONSTRAINT [PK_PRODUCTOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PERSONAS](
	[ID]		  [INT] NOT NULL IDENTITY(1,1),
	[NOMBRE]	  [VARCHAR](50)NOT NULL,
	[APELLIDO]	  [VARCHAR](50)NOT NULL,
	[DNI]		  [VARCHAR](10)NOT NULL,
	[NACIMIENTO]  [DATE]NOT NULL CHECK(DATEDIFF(DAY,NACIMIENTO,GETDATE())>0),
	[EMAIL]		  [VARCHAR](60)NOT NULL,
	[Contraseña]  [VARCHAR](30)NOT NULL,
	[TipoUsuario] [VARCHAR](13)NOT NULL check(TipoUsuario = 'Administrador' or TipoUsuario = 'Usuario' 
											or TipoUsuario = 'Cliente' or TipoUsuario = 'Proveedor'),

 CONSTRAINT [PK_PERSONAS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[USUARIOS](
	[DNI]		  [VARCHAR](10)NOT NULL,
	[DateCreated]  [DATE]NOT NULL CHECK(DATEDIFF(DAY,NACIMIENTO,GETDATE())>0),
	[Pass]  [VARCHAR](30)NOT NULL,
	[TipoUsuario] [VARCHAR](13)NOT NULL check(TipoUsuario = 'Administrador' or TipoUsuario = 'Usuario' 
											or TipoUsuario = 'Cliente' or TipoUsuario = 'Proveedor'),

 CONSTRAINT [PK_PERSONAS] PRIMARY KEY CLUSTERED 
(
	[DNI] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

--Select * from USUARIOS

--insert into USUARIOS ( DNI, Contraseña, TipoUsuario) values ('33294359', '1234', 'Administrador')
--insert into USUARIOS ( DNI, Contraseña, TipoUsuario) values ('1000000', '1111', 'Proveedor')
--insert into USUARIOS ( DNI, Contraseña, TipoUsuario) values ('36475321', '4321', 'Cliente')
--insert into USUARIOS ( DNI, Contraseña, TipoUsuario) values ('4444444', '44', 'Usuario')